### ISSUE TITLE
There is an edge that says: Autoimmune Disease has_phenotype Addison Disease with no evidence.   "Disease has_phenotype Disease" is likely not a valid statement.  Any chance we could drill down a bit more to find out which source we can contact to help? 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [TranslatorSRI/IssueScreenshots#21]
## Steps to reproduce:
search for Addison Disease, click on Zenapax

**Comment by sierra-moxon** [comment]
<img width="736" alt="Screen Shot 2022-09-12 at 12 40 01 PM" src="https://user-images.githubusercontent.com/4561292/189750763-2feaefc8-1aff-41d6-b9a5-7ecfa0592581.png">
<img width="1127" alt="Screen Shot 2022-09-12 at 1 20 20 PM" src="https://user-images.githubusercontent.com/4561292/189751092-415c191a-fec1-42a3-aadb-dc01935a993f.png">

**Comment by maximusunc** [comment]
Hi Sierra, apologies. The Issue Router was switched over to the DataGaps repo, but apparently the environmental variable didn't take effect. I've reposted your issue here: https://github.com/NCATSTranslator/DataGaps/issues/3
